// 注册vux组件
import Vue from 'vue'
import { Grid, GridItem, Flexbox, FlexboxItem, Tab, TabItem, Swiper, SwiperItem, XInput, Group, XTable, Scroller, LoadMore, Divider, Popup, Toast, XButton, Datetime, XHeader, ViewBox, Loading, ConfirmPlugin,Confirm     } from 'vux'

Vue.component('grid', Grid)
Vue.component('grid-item', GridItem)
Vue.component('flexbox', Flexbox)
Vue.component('flexbox-item', FlexboxItem)
Vue.component('tab', Tab)
Vue.component('tab-item', TabItem)
Vue.component('swiper', Swiper)
Vue.component('swiper-item', SwiperItem)
Vue.component('x-input', XInput)
Vue.component('group', Group)
Vue.component('x-table', XTable)
Vue.component('scroller', Scroller)
Vue.component('load-more', LoadMore)
Vue.component('divider', Divider)
Vue.component('popup', Popup)
Vue.component('toast', Toast)
Vue.component('x-button', XButton)
Vue.component('datetime', Datetime)
Vue.component('x-header', XHeader)
Vue.component('view-box', ViewBox)
Vue.component('loading', Loading)
Vue.component('confirm', Confirm)
Vue.use(ConfirmPlugin)
